theme = "kodama"

# The URL the site will be built for
base_url = "https://dlavrent.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

title = "Danylo Lavrentovich"

version = "1.0.1"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[translations]
Biography = "Hello!"
Interests = "Interests"
Education = "Education"
toc = "Table of Contents"
Published = "Published"
Abstract = "Abstract"
volume = "volume"
number = "number"
pages = "pages"

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]

avatar = "img/myheadshot5.jpeg"
favicon = "img/tangerine.png"

# Enter your email
email = "dolavrent[at]gmail.com"

contact_in_index = true

# Additional menu items
# `Name` is what it is displayed, `path` is the url
menu_items = [
   { path = "#contacts", name = "Contact" },
]

# Translation related extra
language_codes = [ "en", ]